console:
  max_message_size_bytes: 409600
logger:
  level: "DEBUG"
session:
  token_expiry_sec: 7200 # 2 hours
socket:
  max_message_size_bytes: 4096 # reserved buffer
  max_request_size_bytes: 131072
runtime:
  env:
    - "GL_AWS_ACCESS_KEY=AKIAT4INFJN5V5JCJVHO"
    - "GL_AWS_SECRET_ACCESS_KEY=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"
    - "GL_AWS_REGION=us-east-1"
    - "GL_AWS_ALIAS_ID=alias-8e00755e-58bb-4575-b602-d10ef0c5b472"
    - "GL_PLACEMENT_QUEUE_NAME=player-session-placement"
    - "GL_PLACEMENT_EVENTS_SQS_URL=https://sqs.us-east-1.amazonaws.com/266852453243/fleet-placement-events.fifo"