console:
  max_message_size_bytes: 409600
logger:
  level: "DEBUG"
session:
  token_expiry_sec: 7200 # 2 hours
socket:
  max_message_size_bytes: 4096 # reserved buffer
  max_request_size_bytes: 131072
runtime:
  env:
    - "GL_AWS_ACCESS_KEY="
    - "GL_AWS_SECRET_ACCESS_KEY="
    - "GL_AWS_REGION="
    - "GL_AWS_ALIAS_ID="
    - "GL_PLACEMENT_QUEUE_NAME="
    - "GL_PLACEMENT_EVENTS_SQS_URL="